[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"
rustflags = [
    "-C", "link-args=-static-libgcc -static-libstdc++",
    "-L", "/opt/vcpkg/installed/x64-mingw-static/lib",
    "-L", "/opt/libs/native",
    "-C", "link-args=-Wl,--start-group -lvpx -lyuv -lopus -laom -ljpeg -lwinpthread -lmingwex -lmingw32 -lmachine-uid -luuid -lole32 -loleaut32 -Wl,--end-group",
    "-C", "link-arg=-lwindowscodecs",
    "-C", "link-arg=-lwinmm",
    "-C", "link-arg=-ldwmapi",
]
